In [1]:
import os
os.path.abspath(os.getcwd())

'c:\\Users\\Leonardo\\Documents\\Repo Github\\People-Analyzer\\SR'

In [ ]:
!python reid\CelebREID_empty\generateDatasetFeatures.py

In [ ]:
import imagenhancer as ie
import numpy as np
import torch
import matplotlib.pyplot as plt 
import cv2 as cv
import sys
sys.argv = ['']

import sys
stdout_sav = sys.stdout
stderr_sav = sys.stderr
fout = open('file.log', 'w')
sys.stdout = fout
sys.stderr = fout

model_path_x4 = '.\\RealESRGANmaster\\weights\\RealESRGAN_x4plus.pth'

enhancer = ie.RealESRGANx2(model_path = model_path_x4,scale_= 4)

from reid.CelebREID_empty.searchImage import search

filename = r'C:\Users\Leonardo\Documents\Universita\CVCS\PRJ\reid\CelebREID_empty\testImages\313_001.jpg'
name_img = filename[-11:]
filenameSR = filename[:-12] +'\\SR\\'+name_img

print(f"filename: {filename}\nnameimg: {name_img}\nfilenameSR: {filenameSR}")


# Check metrics for a standard image AA
fig = search(SR=False)[0]
label = fig._suptitle.get_text()
fig.suptitle(label+"\nStandard Image.")

print("..------------------- First search")

import cv2 as cv
img = cv.imread(filename)
img = cv.cvtColor(img,cv.COLOR_BGR2RGB)

import matplotlib.pyplot as plt

# Working on the quality of the image
img_res = ie.downscale(enhancer.filtering(enhancer.upscale(img)),2)


#upsample AB
img_up = enhancer.upscale(img)
cv.imwrite(filenameSR ,cv.cvtColor(img_up,cv.COLOR_RGB2BGR))
fig = search(SR=True)[0]
label = fig._suptitle.get_text()
fig.suptitle(label+"\nOnly Upsample.")

#filtering AC
img_up_filt = enhancer.filtering(img_up)
cv.imwrite(filenameSR ,cv.cvtColor(img_up_filt,cv.COLOR_RGB2BGR))
fig = search(SR=True)[0]
label = fig._suptitle.get_text()
fig.suptitle(label+"\nUpsample + sharpening.")

#down sampling AD
img_up_filt_down = ie.downscale(img_up_filt,2)
cv.imwrite(filenameSR ,cv.cvtColor(img_up_filt_down,cv.COLOR_RGB2BGR))
fig = search(SR=True)[0]
label = fig._suptitle.get_text()
fig.suptitle(label+"\nUpsample + sharpening + downscale")

#reset

#filtering AE !
img_filt = enhancer.filtering(img)
cv.imwrite(filenameSR ,cv.cvtColor(img_filt,cv.COLOR_RGB2BGR))
fig = search(SR=True)[0]
label = fig._suptitle.get_text()
fig.suptitle(label+"\nOnly sharpening.")

#upsample AF
img_filt_up = enhancer.upscale(img_filt)
cv.imwrite(filenameSR ,cv.cvtColor(img_filt_up,cv.COLOR_RGB2BGR))
fig = search(SR=True)[0]
label = fig._suptitle.get_text()
fig.suptitle(label+"\nSharpening + Upscale")


sys.stdout = stdout_sav
sys.stderr = stderr_sav
fout.close()

# Save the superresoluted image

cv.imwrite(filenameSR ,cv.cvtColor(img_res,cv.COLOR_RGB2BGR))
# Check metrics for the transformed one

fig = plt.figure()

fig.add_subplot(1,2,1)

plt.imshow(img)
fig.add_subplot(1,2,2)

plt.imshow(img_res)


In [19]:
# Prendo un immagine per ogni persona dal validation set

# reid\CelebREID_empty\prcc.tar\prcc\prcc\rgb\val
import random
import os
import cv2 as cv
import shutil
import matplotlib.pyplot as plt
source_dir = os.getcwd() + '\\reid\\CelebREID_empty\\prcc.tar\\prcc\\prcc\\rgb\\val\\'
VAL_PATH = r'reid\CelebREID_empty\prcc.tar\prcc\prcc\rgb\val'
target_dir = os.getcwd() + r'\reid\CelebREID_empty\testImages'

for i in os.listdir(VAL_PATH):
    # i: folder for every person in the dataset
    files=os.listdir(VAL_PATH+"\\"+i)
    d=random.choice(files)  # d namefiles for the person
    name_comp = i+"_"+d[-7:]
    shutil.copy(source_dir+i+"\\"+d, target_dir+"\\"+name_comp) # reid\CelebREID_empty\testImages

In [1]:
import os
import cv2 as cv
import imagenhancer as ie

model_path_x4 = '.\\RealESRGANmaster\\weights\\RealESRGAN_x4plus.pth'
enhancer = ie.RealESRGANx2(model_path = model_path_x4,scale_= 4)
op_list=["","UP","FILT","UP_FILT","FILT_UP","UP_FILT_DOWN"]

c:\Users\Leonardo\anaconda3\envs\generic\lib\site-packages\tqdm\auto.py:22: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [ ]:
# Complete, do this when you are just starting out
TEST_DIR = os.path.abspath(os.getcwd())+r"\reid\CelebREID_empty\testimages"

for i in os.listdir(TEST_DIR):
    if i[-4:] == '.jpg':
        img = cv.cvtColor(cv.imread(TEST_DIR+"\\"+i), cv.COLOR_BGR2RGB)
        res = img
        for ind, op in enumerate(op_list):
            if op == "UP":
                res = enhancer.upscale(img)
                if res == img:
                    print("ERROR")

            elif op == "FILT":
                res = enhancer.filtering(img)

            elif op == "FILT_UP":
                res = enhancer.filt_up(img)
            
            elif op == "UP_FILT":
                res = enhancer.up_filt(img)

            
            elif op == "UP_FILT_DOWN":
                res = enhancer.up_filt_down(img)

            res_filename = TEST_DIR+"\\"+op+"\\"+i
            cv.imwrite(res_filename, cv.cvtColor(res, cv.COLOR_RGB2BGR))

In [2]:
# Do this when you are testing a particular operation
TEST_DIR = os.path.abspath(os.getcwd())+r"\reid\CelebREID_empty\testimages"

for i in os.listdir(TEST_DIR):
    if i[-4:] == '.jpg':
        img = cv.cvtColor(cv.imread(TEST_DIR+"\\"+i), cv.COLOR_BGR2RGB)
        res = img
        for ind, op in enumerate(op_list):
            if op == "UP":
                res = enhancer.upscale(img)
                if res == img:
                    print("ERROR")

            elif op == "FILT":
                res = enhancer.filtering(img,0)

            elif op == "FILT_UP":
                res = enhancer.filt_up(img)
            
            elif op == "UP_FILT":
                res = enhancer.up_filt(img)

            
            elif op == "UP_FILT_DOWN":
                res = enhancer.up_filt_down(img)

            res_filename = TEST_DIR+"\\"+op+"\\"+i
            cv.imwrite(res_filename, cv.cvtColor(res, cv.COLOR_RGB2BGR))

C:\Users\Leonardo\AppData\Local\Temp\ipykernel_15324\2331656485.py:11: DeprecationWarning: elementwise comparison failed; this will raise an error in the future.
  if res == img:


W: 178, H: 490
W: 190, H: 546
W: 154, H: 466
W: 246, H: 716
W: 182, H: 558
W: 210, H: 690
W: 190, H: 586


In [3]:
from reid.CelebREID_empty.searchImage import search

results = list()

for i in op_list:
    tmp_dict = dict()
    TEST_DIR = os.path.abspath(os.getcwd())+r"\reid\CelebREID_empty\testimages"+"\\"+i
    print(TEST_DIR)
    tmp_dict = search(True,TEST_DIR)
    results.append(tmp_dict)

c:\Users\Leonardo\anaconda3\envs\generic\lib\site-packages\sklearn\utils\deprecation.py:144: FutureWarning: The sklearn.metrics.base module is  deprecated in version 0.22 and will be removed in version 0.24. The corresponding classes / functions should instead be imported from sklearn.metrics. Anything that cannot be imported from sklearn.metrics is now part of the private API.
  warnings.warn(message, FutureWarning)
c:\Users\Leonardo\anaconda3\envs\generic\lib\site-packages\torchvision\transforms\transforms.py:329: UserWarning: Argument 'interpolation' of type int is deprecated since 0.13 and will be removed in 0.15. Please use InterpolationMode enum.
  warnings.warn(
c:\Users\Leonardo\anaconda3\envs\generic\lib\site-packages\torchvision\models\_utils.py:208: UserWarning: The parameter 'pretrained' is deprecated since 0.13 and may be removed in the future, please use 'weights' instead.
  warnings.warn(
c:\Users\Leonardo\anaconda3\envs\generic\lib\site-packages\torchvision\models\_util

c:\Users\Leonardo\Documents\Repo Github\People-Analyzer\SR
c:\Users\Leonardo\Documents\Repo Github\People-Analyzer\SR\reid\CelebREID_empty\testimages\
c:\Users\Leonardo\Documents\Repo Github\People-Analyzer\SR\reid\CelebREID_empty\testimages\
=> Loaded checkpoint 'C:\Users\Leonardo\Documents\Universita\CVCS\PRJ\reid\model.pth.tar'


c:\Users\Leonardo\Documents\Repo Github\People-Analyzer\SR\reid\CelebREID_empty\reid\evaluator.py:20: UserWarning: volatile was removed and now has no effect. Use `with torch.no_grad():` instead.
  inputs = Variable(inputs, volatile=True)


10-Precision: 0.3 - Recall: 0.1034
10-Precision: 0.5 - Recall: 0.1136
10-Precision: 0.4 - Recall: 0.1176
10-Precision: 0.3 - Recall: 0.0811
10-Precision: 0.3 - Recall: 0.0882
10-Precision: 0.7 - Recall: 0.1892
10-Precision: 0.5 - Recall: 0.1515
c:\Users\Leonardo\Documents\Repo Github\People-Analyzer\SR\reid\CelebREID_empty\testimages\UP
c:\Users\Leonardo\Documents\Repo Github\People-Analyzer\SR\reid\CelebREID_empty\testimages\UP


c:\Users\Leonardo\anaconda3\envs\generic\lib\site-packages\torchvision\transforms\transforms.py:329: UserWarning: Argument 'interpolation' of type int is deprecated since 0.13 and will be removed in 0.15. Please use InterpolationMode enum.
  warnings.warn(
c:\Users\Leonardo\anaconda3\envs\generic\lib\site-packages\torchvision\models\_utils.py:208: UserWarning: The parameter 'pretrained' is deprecated since 0.13 and may be removed in the future, please use 'weights' instead.
  warnings.warn(
c:\Users\Leonardo\anaconda3\envs\generic\lib\site-packages\torchvision\models\_utils.py:223: UserWarning: Arguments other than a weight enum or `None` for 'weights' are deprecated since 0.13 and may be removed in the future. The current behavior is equivalent to passing `weights=DenseNet121_Weights.IMAGENET1K_V1`. You can also use `weights=DenseNet121_Weights.DEFAULT` to get the most up-to-date weights.
  warnings.warn(msg)


=> Loaded checkpoint 'C:\Users\Leonardo\Documents\Universita\CVCS\PRJ\reid\model.pth.tar'


c:\Users\Leonardo\Documents\Repo Github\People-Analyzer\SR\reid\CelebREID_empty\reid\evaluator.py:20: UserWarning: volatile was removed and now has no effect. Use `with torch.no_grad():` instead.
  inputs = Variable(inputs, volatile=True)


10-Precision: 0.4 - Recall: 0.1379
10-Precision: 0.7 - Recall: 0.1591
10-Precision: 0.3 - Recall: 0.0882
10-Precision: 0.4 - Recall: 0.1081
10-Precision: 0.3 - Recall: 0.0882
10-Precision: 0.3 - Recall: 0.0811
10-Precision: 0.5 - Recall: 0.1515
c:\Users\Leonardo\Documents\Repo Github\People-Analyzer\SR\reid\CelebREID_empty\testimages\FILT
c:\Users\Leonardo\Documents\Repo Github\People-Analyzer\SR\reid\CelebREID_empty\testimages\FILT


c:\Users\Leonardo\anaconda3\envs\generic\lib\site-packages\torchvision\transforms\transforms.py:329: UserWarning: Argument 'interpolation' of type int is deprecated since 0.13 and will be removed in 0.15. Please use InterpolationMode enum.
  warnings.warn(
c:\Users\Leonardo\anaconda3\envs\generic\lib\site-packages\torchvision\models\_utils.py:208: UserWarning: The parameter 'pretrained' is deprecated since 0.13 and may be removed in the future, please use 'weights' instead.
  warnings.warn(
c:\Users\Leonardo\anaconda3\envs\generic\lib\site-packages\torchvision\models\_utils.py:223: UserWarning: Arguments other than a weight enum or `None` for 'weights' are deprecated since 0.13 and may be removed in the future. The current behavior is equivalent to passing `weights=DenseNet121_Weights.IMAGENET1K_V1`. You can also use `weights=DenseNet121_Weights.DEFAULT` to get the most up-to-date weights.
  warnings.warn(msg)


=> Loaded checkpoint 'C:\Users\Leonardo\Documents\Universita\CVCS\PRJ\reid\model.pth.tar'


c:\Users\Leonardo\Documents\Repo Github\People-Analyzer\SR\reid\CelebREID_empty\reid\evaluator.py:20: UserWarning: volatile was removed and now has no effect. Use `with torch.no_grad():` instead.
  inputs = Variable(inputs, volatile=True)


10-Precision: 0.3 - Recall: 0.1034
10-Precision: 0.8 - Recall: 0.1818
10-Precision: 0.3 - Recall: 0.0882
10-Precision: 0.4 - Recall: 0.1081
10-Precision: 0.4 - Recall: 0.1176
10-Precision: 0.8 - Recall: 0.2162
10-Precision: 0.7 - Recall: 0.2121
c:\Users\Leonardo\Documents\Repo Github\People-Analyzer\SR\reid\CelebREID_empty\testimages\UP_FILT
c:\Users\Leonardo\Documents\Repo Github\People-Analyzer\SR\reid\CelebREID_empty\testimages\UP_FILT


c:\Users\Leonardo\anaconda3\envs\generic\lib\site-packages\torchvision\transforms\transforms.py:329: UserWarning: Argument 'interpolation' of type int is deprecated since 0.13 and will be removed in 0.15. Please use InterpolationMode enum.
  warnings.warn(
c:\Users\Leonardo\anaconda3\envs\generic\lib\site-packages\torchvision\models\_utils.py:208: UserWarning: The parameter 'pretrained' is deprecated since 0.13 and may be removed in the future, please use 'weights' instead.
  warnings.warn(
c:\Users\Leonardo\anaconda3\envs\generic\lib\site-packages\torchvision\models\_utils.py:223: UserWarning: Arguments other than a weight enum or `None` for 'weights' are deprecated since 0.13 and may be removed in the future. The current behavior is equivalent to passing `weights=DenseNet121_Weights.IMAGENET1K_V1`. You can also use `weights=DenseNet121_Weights.DEFAULT` to get the most up-to-date weights.
  warnings.warn(msg)


=> Loaded checkpoint 'C:\Users\Leonardo\Documents\Universita\CVCS\PRJ\reid\model.pth.tar'


c:\Users\Leonardo\Documents\Repo Github\People-Analyzer\SR\reid\CelebREID_empty\reid\evaluator.py:20: UserWarning: volatile was removed and now has no effect. Use `with torch.no_grad():` instead.
  inputs = Variable(inputs, volatile=True)


10-Precision: 0.4 - Recall: 0.1379
10-Precision: 0.7 - Recall: 0.1591
10-Precision: 0.0 - Recall: 0.0
10-Precision: 0.4 - Recall: 0.1081
10-Precision: 0.2 - Recall: 0.0588
10-Precision: 0.3 - Recall: 0.0811
10-Precision: 0.4 - Recall: 0.1212
c:\Users\Leonardo\Documents\Repo Github\People-Analyzer\SR\reid\CelebREID_empty\testimages\FILT_UP
c:\Users\Leonardo\Documents\Repo Github\People-Analyzer\SR\reid\CelebREID_empty\testimages\FILT_UP


c:\Users\Leonardo\anaconda3\envs\generic\lib\site-packages\torchvision\transforms\transforms.py:329: UserWarning: Argument 'interpolation' of type int is deprecated since 0.13 and will be removed in 0.15. Please use InterpolationMode enum.
  warnings.warn(
c:\Users\Leonardo\anaconda3\envs\generic\lib\site-packages\torchvision\models\_utils.py:208: UserWarning: The parameter 'pretrained' is deprecated since 0.13 and may be removed in the future, please use 'weights' instead.
  warnings.warn(
c:\Users\Leonardo\anaconda3\envs\generic\lib\site-packages\torchvision\models\_utils.py:223: UserWarning: Arguments other than a weight enum or `None` for 'weights' are deprecated since 0.13 and may be removed in the future. The current behavior is equivalent to passing `weights=DenseNet121_Weights.IMAGENET1K_V1`. You can also use `weights=DenseNet121_Weights.DEFAULT` to get the most up-to-date weights.
  warnings.warn(msg)


=> Loaded checkpoint 'C:\Users\Leonardo\Documents\Universita\CVCS\PRJ\reid\model.pth.tar'


c:\Users\Leonardo\Documents\Repo Github\People-Analyzer\SR\reid\CelebREID_empty\reid\evaluator.py:20: UserWarning: volatile was removed and now has no effect. Use `with torch.no_grad():` instead.
  inputs = Variable(inputs, volatile=True)


10-Precision: 0.4 - Recall: 0.1379
10-Precision: 0.6 - Recall: 0.1364
10-Precision: 0.3 - Recall: 0.0882
10-Precision: 0.4 - Recall: 0.1081
10-Precision: 0.3 - Recall: 0.0882
10-Precision: 0.3 - Recall: 0.0811
10-Precision: 0.5 - Recall: 0.1515
c:\Users\Leonardo\Documents\Repo Github\People-Analyzer\SR\reid\CelebREID_empty\testimages\UP_FILT_DOWN
c:\Users\Leonardo\Documents\Repo Github\People-Analyzer\SR\reid\CelebREID_empty\testimages\UP_FILT_DOWN


c:\Users\Leonardo\anaconda3\envs\generic\lib\site-packages\torchvision\transforms\transforms.py:329: UserWarning: Argument 'interpolation' of type int is deprecated since 0.13 and will be removed in 0.15. Please use InterpolationMode enum.
  warnings.warn(
c:\Users\Leonardo\anaconda3\envs\generic\lib\site-packages\torchvision\models\_utils.py:208: UserWarning: The parameter 'pretrained' is deprecated since 0.13 and may be removed in the future, please use 'weights' instead.
  warnings.warn(
c:\Users\Leonardo\anaconda3\envs\generic\lib\site-packages\torchvision\models\_utils.py:223: UserWarning: Arguments other than a weight enum or `None` for 'weights' are deprecated since 0.13 and may be removed in the future. The current behavior is equivalent to passing `weights=DenseNet121_Weights.IMAGENET1K_V1`. You can also use `weights=DenseNet121_Weights.DEFAULT` to get the most up-to-date weights.
  warnings.warn(msg)


=> Loaded checkpoint 'C:\Users\Leonardo\Documents\Universita\CVCS\PRJ\reid\model.pth.tar'


c:\Users\Leonardo\Documents\Repo Github\People-Analyzer\SR\reid\CelebREID_empty\reid\evaluator.py:20: UserWarning: volatile was removed and now has no effect. Use `with torch.no_grad():` instead.
  inputs = Variable(inputs, volatile=True)


10-Precision: 0.4 - Recall: 0.1379
10-Precision: 0.7 - Recall: 0.1591
10-Precision: 0.4 - Recall: 0.1176
10-Precision: 0.4 - Recall: 0.1081
10-Precision: 0.1 - Recall: 0.0294
10-Precision: 0.3 - Recall: 0.0811
10-Precision: 0.4 - Recall: 0.1212


In [4]:
#primo indice raggruppa per operazione
#secondo indice dizionario per immagineb
p_list={}
r_list={}

for i in results:    
    l = len(i)
    
    op = i[0]["operation"]
    if op=="":
        op="std"
    p_list[op]=0
    r_list[op]=0
    for ind in i:
        p_list[op]+=ind["precision"]/l
        r_list[op]+=ind["recall"]/l

In [5]:
for i in p_list.keys():
    print(f"precision {i} : {p_list[i]}")
    print(f"recall {i} : {r_list[i]}")
    print("___________________________")

precision std : 0.4285714285714286
recall std : 0.12065714285714285
___________________________
precision UP : 0.41428571428571437
recall UP : 0.1163
___________________________
precision FILT : 0.5285714285714286
recall FILT : 0.14677142857142855
___________________________
precision UP_FILT : 0.3428571428571429
recall UP_FILT : 0.09517142857142857
___________________________
precision FILT_UP : 0.4
recall FILT_UP : 0.11305714285714286
___________________________
precision UP_FILT_DOWN : 0.3857142857142858
recall UP_FILT_DOWN : 0.10777142857142856
___________________________


In [12]:
len(results) #Primo indice indica l'operazione

6

In [13]:
len(results[0]) #secondo indice l'immagine

19

In [34]:
import numpy as np
p_std = list()
for op in results[0]:
    p_std.append(op["precision"])

p_std = np.array(p_std)

In [43]:
measure = list()
for i,op in enumerate(results):
    p_up = list()
    for i in op:
        p_up.append(i["precision"])
    measure.append(np.array(p_up))


In [56]:
measure

[array([0.3, 0.5, 0.4, 0.9, 0.2, 0.6, 0.3, 0.6, 0.3, 0.3, 0.3, 0.9, 0.8,
        0.3, 0.7, 0.4, 0.9, 0.9, 0.5]),
 array([0.4, 0.7, 0.3, 0.9, 0.2, 0.5, 0.4, 0.3, 0.3, 0.2, 0.3, 0.8, 0.6,
        0.4, 0.3, 0.5, 0.9, 0.8, 0.4]),
 array([0.3, 0.8, 0.3, 0.9, 0.2, 0.6, 0.4, 0.5, 0.1, 0.3, 0.4, 0.9, 0.7,
        0.3, 0.7, 0.4, 0.9, 0.9, 0.7]),
 array([0.4, 0.5, 0.5, 0.9, 0.2, 0.5, 0.4, 0.3, 0.2, 0.2, 0.4, 0.9, 0.6,
        0.6, 0.3, 0.5, 0.9, 0.8, 0.5]),
 array([0.3, 0.2, 0.1, 0.7, 0.2, 0.6, 0.3, 0.4, 0. , 0.3, 0.3, 0.7, 0.6,
        0. , 0.3, 0.4, 0.9, 0.5, 0.1]),
 array([0.4, 0.5, 0.5, 0.9, 0.2, 0.5, 0.4, 0.3, 0.3, 0.2, 0.4, 0.9, 0.6,
        0.6, 0.3, 0.5, 0.9, 0.8, 0.6])]

In [ ]:
p_up